<?php
/* /public/create_lab_order.php   – 28 Apr 2025 (v3)
 * • Ensures MyriadPro-Regular is the active font for every PDF
 * • Headings centred fix + earlier font-path patch retained
 * • MODIFIED: Makes MRN optional. If blank, a new patient is created
 * with a random MRN, requiring only Name and Age.
 */

/*────────  FPDF font path must be first  ────────*/
if (!defined('FPDF_FONTPATH')) {
    define('FPDF_FONTPATH', __DIR__ . '/includes/font/');
}

/*────────  core includes  ────────*/
session_start();
if (!isset($_SESSION['user'])) {
    header('Location: login.php');
    exit;
}

require_once __DIR__ . '/includes/config.php';   // $pdo
require_once __DIR__ . '/includes/fpdf.php';
require_once __DIR__ . '/includes/code128.php';

/*────────  authorisation  ────────*/
if (!in_array((int)($_SESSION['user']['group_id'] ?? 0), [1, 4, 5, 6, 8, 10, 23], true)) {
    header('HTTP/1.1 403 Forbidden');
    exit('Access denied.');
}
$uname = $_SESSION['user']['username'] ?? 'unknown';
$ufull = $_SESSION['user']['full_name'] ?? $uname;

/*────────  helpers  ────────*/
function getPatientByMrn(PDO $pdo, string $mrn): array|false
{
    $st = $pdo->prepare(
        "SELECT mrn, full_name, gender, age, age_unit
         FROM patients
         WHERE mrn = ?
         LIMIT 1"
    );
    $st->execute([$mrn]);
    return $st->fetch(PDO::FETCH_ASSOC);
}

/**
 * Generates a unique 8-digit patient MRN not in the database.
 */
function generateUniqueMrn(PDO $pdo): string
{
    $st = $pdo->prepare("SELECT 1 FROM patients WHERE mrn = ?");
    do {
        $mrn = (string) mt_rand(10000000, 99999999);
        $st->execute([$mrn]);
    } while ($st->fetchColumn() !== false);
    return $mrn;
}

/**
 * Inserts a new patient with default values.
 */
function insertNewPatient(PDO $pdo, string $mrn, string $name, int $age): void
{
    $st = $pdo->prepare(
        "INSERT INTO patients (mrn, full_name, age, age_unit, gender)
         VALUES (?, ?, ?, 'years', 'N/A')"
    );
    $st->execute([$mrn, $name, $age]);
}


/*────────  Code128 patch  ────────*/
class Code128Fixed extends PDF_Code128
{
    function __construct()
    {
        parent::__construct();
        foreach (['A', 'B', 'C'] as $s) {
            if (isset($this->SetFrom[$s]) && !is_array($this->SetFrom[$s])) {
                $this->SetFrom[$s] = str_split($this->SetFrom[$s]);
            }
        }
    }
}

/*────────  custom PDF  ────────*/
class LabPDF extends Code128Fixed
{
    function __construct()
    {
        parent::__construct('P', 'mm', 'A4');

        /*---------------------------------------------------------
         * Register the custom font and **select it immediately**.
         * If registration fails, fall back gracefully to Arial.
         *--------------------------------------------------------*/
        try {
            $this->AddFont('MyriadPro-Regular', '', 'MyriadPro-Regular.php');
            $this->SetFont('MyriadPro-Regular', '', 10);   // ← active font
        } catch (Exception $e) {
            // Fallback – still allows PDF to generate
            $this->SetFont('Arial', '', 10);
        }
    }

    function family()
    {
        return $this->FontFamily;
    }

    function Header()
    {
        $W   = $this->GetPageWidth();
        $logo = __DIR__ . '/media/logo-print.png';
        if (is_readable($logo)) {
            $this->Image($logo, ($W - 80) / 2, 10, 80);
            $this->Ln(35);
        }
        $this->SetFont($this->FontFamily, '', 16);
        $this->SetTextColor(100, 100, 100);
        $this->Cell(0, 7, 'hospital0', 0, 1, 'C');
        $this->SetFont($this->FontFamily, '', 12);
        $this->Cell(0, 5, 'www.hospital0', 0, 1, 'C');
        $this->Ln(2);
        $this->SetDrawColor(150, 150, 150);
        $this->SetLineWidth(.4);
        $x = ($W - 140) / 2;
        $y = $this->GetY() + 2;
        $this->Line($x, $y, $x + 140, $y);
        $this->Ln(10);
    }

    function Footer()
    {
        global $ufull;
        $this->SetY(-20);
        $this->SetFont($this->FontFamily, '', 9);
        $this->SetTextColor(100, 100, 100);
        $now = new DateTime('now', new DateTimeZone('Asia/Karachi'));
        $this->Cell(
            0,
            6,
            'Invoice generated by ' . $ufull . ' on ' . $now->format('Y-m-d H:i:s T'),
            0,
            1,
            'C'
        );
        $this->Ln(1);
        $this->SetFont($this->FontFamily, '', 10);
        $this->Cell(0, 6, 'hospital0', 0, 1, 'C');
    }

    function Row($lab, $val, $labW = 45, $h = 7)
    {
        $w = $this->GetPageWidth() - $this->lMargin - $this->rMargin - $labW;
        $this->SetFont($this->FontFamily, '', 11);
        $this->Cell($labW, $h, $lab, 0, 0);
        $x = $this->GetX();
        $y = $this->GetY();
        $this->MultiCell($w, $h, $val);
        $this->SetXY($this->lMargin, max($y + $h, $this->GetY()));
    }

    function HeadRow($h1, $h2)
    {
        $tot = $this->GetPageWidth() - $this->lMargin - $this->rMargin;
        $w   = [($tot - 45), 45];
        $this->SetFont($this->FontFamily, '', 11);
        $this->SetFillColor(220, 220, 220);
        $this->Cell($w[0], 7, $h1, 1, 0, 'C', true);
        $this->Cell($w[1], 7, $h2, 1, 1, 'C', true);
        return $w;
    }

    function DataRow($row, $w)
    {
        $this->SetFont($this->FontFamily, '', 10);
        $this->SetDrawColor(200, 200, 200);
        $this->Rect($this->GetX(), $this->GetY(), $w[0], 6);
        $this->Cell($w[0], 6, $row[0], 0, 0);
        $this->Rect($this->GetX(), $this->GetY(), $w[1], 6);
        $this->Cell($w[1], 6, $row[1], 0, 1, 'R');
    }
}

/*────────  flash  ────────*/
$err  = $_SESSION['error_message'] ?? '';
$ok   = $_SESSION['success_message'] ?? '';
$pdf  = $_SESSION['pdfLink'] ?? null;
unset($_SESSION['error_message'], $_SESSION['success_message'], $_SESSION['pdfLink']);

$pData   = $_SESSION['fetched_patient_data'] ?? null;
$mrnVal  = $_SESSION['create_order_mrn'] ?? '';
$trigger = isset($_SESSION['trigger_print']);
unset($_SESSION['trigger_print']);

/*────────  active tests  ────────*/
$tests = $pdo->query(
    "SELECT test_id, test_name, test_price
     FROM lab_tests
     WHERE is_active = TRUE
     ORDER BY test_name"
)->fetchAll(PDO::FETCH_ASSOC);

/*────────  POST handling  ────────*/
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $act = $_POST['action'] ?? '';
    $pdo->beginTransaction();
    try {
        /* fetch or create patient */
        if ($act === 'fetch_patient') {
            $mrn = trim($_POST['mrn'] ?? '');

            if ($mrn !== '') { // MRN was entered, use existing logic
                if (!$pat = getPatientByMrn($pdo, $mrn)) {
                    $_SESSION['error_message'] = 'No patient with MRN "' . htmlspecialchars($mrn) . '"';
                    $_SESSION['create_order_mrn'] = $mrn;
                } else {
                    $_SESSION['fetched_patient_data'] = $pat;
                    $_SESSION['create_order_mrn']     = $mrn;
                }
            } else { // MRN is blank, create a new patient
                $fullName = trim($_POST['full_name'] ?? '');
                $age      = filter_var($_POST['age'] ?? '', FILTER_VALIDATE_INT);

                if (empty($fullName) || $age === false || $age <= 0) {
                    throw new Exception('Full Name and a valid Age are required when MRN is not provided.');
                }

                $newMrn = generateUniqueMrn($pdo);
                insertNewPatient($pdo, $newMrn, $fullName, $age);

                // Set session data for the newly created patient
                $_SESSION['fetched_patient_data'] = [
                    'mrn'       => $newMrn,
                    'full_name' => $fullName,
                    'gender'    => 'N/A',
                    'age'       => $age,
                    'age_unit'  => 'years',
                ];
                $_SESSION['create_order_mrn'] = $newMrn;
            }
            $pdo->commit();
            header('Location: create_lab_order.php');
            exit;
        }


        /* create order + PDF */
        if ($act === 'create_order') {
            $mrn      = trim($_POST['mrn'] ?? '');
            $selected = $_POST['selected_tests'] ?? [];
            if ($mrn === '') {
                throw new Exception('MRN missing.');
            }
            if (!$pat = getPatientByMrn($pdo, $mrn)) {
                throw new Exception('Invalid MRN.');
            }
            if (!$selected) {
                throw new Exception('Select at least one test.');
            }

            // validate tests
            $ph  = rtrim(str_repeat('?,', count($selected)), ',');
            $chk = $pdo->prepare(
                "SELECT test_id, test_name, test_price
                 FROM lab_tests
                 WHERE test_id IN ($ph) AND is_active = TRUE"
            );
            $chk->execute($selected);
            $rows = $chk->fetchAll(PDO::FETCH_ASSOC);
            if (count($rows) !== count($selected)) {
                throw new Exception('Inactive/invalid test selected.');
            }

            $total = array_sum(array_column($rows, 'test_price'));

            // create order
            $pdo->prepare(
                "INSERT INTO lab_orders
                 (patient_mrn, ordered_by_user, status, total_amount, order_date)
                 VALUES (?, ?, 'Pending', ?, NOW())"
            )->execute([$mrn, $uname, $total]);
            $oid = $pdo->lastInsertId();

            // items
            $ins = $pdo->prepare(
                "INSERT INTO lab_order_items (order_id, test_id)
                 VALUES (?, ?)"
            );
            foreach ($selected as $tid) {
                $ins->execute([$oid, $tid]);
            }

            /* PDF path */
            $dir = __DIR__ . '/lab_invoices/';
            if (!is_dir($dir)) {
                @mkdir($dir, 0775, true);
            }
            $safeMrn = preg_replace('/[^A-Za-z0-9_-]/', '_', $mrn);
            $file    = $dir . "LabInvoice_{$safeMrn}_{$oid}.pdf";
            for ($i = 1; file_exists($file); $i++) {
                $file = $dir . "LabInvoice_{$safeMrn}_{$oid}_{$i}.pdf";
            }
            $rel = 'lab_invoices/' . basename($file);

            /* generate PDF */
            $pdfDoc = new LabPDF();
            $f      = $pdfDoc->family();
            $pdfDoc->SetMargins(15, 10);
            $pdfDoc->SetAutoPageBreak(true, 25);
            $pdfDoc->AddPage();
            $pdfDoc->SetFont($f, '', 16);
            $pdfDoc->Cell(0, 8, 'LABORATORY ORDER INVOICE', 0, 1, 'C');
            $pdfDoc->Ln(8);

            $pdfDoc->SetFont($f, '', 12);
            $pdfDoc->Row('Patient Name:', $pat['full_name']);
            $pdfDoc->Row('MRN:', $pat['mrn']);
            $ageTxt = $pat['age'] > 0 ? $pat['age'] . ' ' . $pat['age_unit'] : 'N/A';
            $pdfDoc->Row('Age:', $ageTxt);
            $pdfDoc->Row('Gender:', $pat['gender']);
            $pdfDoc->Ln(5);
            $pdfDoc->Row('Order ID:', $oid);
            $pdfDoc->Row('Order Date:', date('d M Y, h:i A'));
            $pdfDoc->Ln(10);

            /* barcode */
            $barW = 80;
            $x    = ($pdfDoc->GetPageWidth() - $barW) / 2;
            $y    = $pdfDoc->GetY();
            $pdfDoc->Code128($x, $y, (string) $oid, $barW, 20);
            $pdfDoc->SetY($y + 22);

            $pdfDoc->Cell(0, 8, 'Ordered Tests:', 0, 1, 'L');
            $w = $pdfDoc->HeadRow('Test Name', 'Price (PKR)');
            foreach ($rows as $r) {
                $pdfDoc->DataRow(
                    [$r['test_name'], number_format($r['test_price'], 2)],
                    $w
                );
            }
            $pdfDoc->Ln(5);
            $pdfDoc->Cell($w[0], 8, 'Total Amount:', 0, 0, 'R');
            $pdfDoc->Cell(
                $w[1],
                8,
                'PKR ' . number_format($total, 2),
                1,
                1,
                'R'
            );

            $pdfDoc->Output('F', $file);

  /* ---------- NEW: auto-ledger entry ---------- */
            $pdo->prepare(
              "INSERT INTO labledger (datetime,description,amount,user)
               VALUES (NOW(),?,?,?)"
            )->execute([basename($file), $total, $uname]);  // credit = +ve amount

            $pdo->commit();
            $_SESSION['success_message'] = 'Lab order #' . $oid . ' created.';
            $_SESSION['pdfLink']        = $rel;
            $_SESSION['trigger_print']  = true;
            unset($_SESSION['fetched_patient_data'], $_SESSION['create_order_mrn']);
            header('Location: create_lab_order.php');
            exit;
        }

        $pdo->commit();
    } catch (Exception $e) {
        if ($pdo->inTransaction()) {
            $pdo->rollBack();
        }
        $_SESSION['error_message'] = 'Error: ' . $e->getMessage();
        header('Location: create_lab_order.php');
        exit;
    }
}

/* clear patient via GET already handled above */

/*──────────  HTML  ──────────*/

/*────────  clear patient  ────────*/
if (isset($_GET['clear_patient'])) {
    unset($_SESSION['fetched_patient_data'], $_SESSION['create_order_mrn']);
    header('Location: create_lab_order.php');
    exit;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>hospital0 - Create Lab Order — hospital0</title>
<link rel="icon" href="/media/sitelogo.png">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="assets/css/style.css">
<style>
.tests-box {
    max-height: 350px;
    overflow-y: auto;
    border: 1px solid #555;
    padding: 15px;
    background: rgba(0, 0, 0, .1);
    border-radius: 4px;
    text-align: left;
}
.patient-box {
    background: rgba(0, 0, 0, .15);
    border: 1px solid rgba(255, 255, 255, .15);
    border-radius: 5px;
    padding: 16px;
    margin-top: 20px;
    text-align: left;
}
.banner {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 12px 18px;
    margin: 20px 0;
    border-radius: 4px;
}
.banner-err { background: #c62828; }
.banner-ok  { background: #2e7d32; }
.pdf-link-btn {
    margin-left: 15px;
    background: #616161 !important;
    color: #fff !important;
}
input[type=search] {
    background: rgba(0, 0, 0, .15) !important;
    color: #fff !important;
}
input[type=search]:focus {
    background: rgba(0, 0, 0, .25) !important;
}
input[type=text]:focus + label,
input[type=number]:focus + label,
input[type=search]:focus + label,
input[type=text]:not(:placeholder-shown) + label,
input[type=number]:not(:placeholder-shown) + label,
input[type=search].active + label {
    transform: translateY(-14px) scale(.8) !important;
    transform-origin: left top;
    color: #1de9b6 !important;
}
</style>
</head>
<body>

<?php include __DIR__ . '/includes/header.php'; ?>
<hr class="white-line-header">

<main>
<div class="container">

  <div class="center-align" style="margin-bottom:40px;">
    <h1 class="site-title" style="margin:0;">hospital0</h1>
    <h5 class="lab-title" style="margin:4px 0 12px 0;">Laboratory Management System</h5>
    <h4 class="tab-title" style="margin:0;">Create New Lab Order</h4>
  </div>

  <?php if ($err): ?>
      <div class="banner banner-err">
          <i class="material-icons">error_outline</i><?= htmlspecialchars($err) ?>
      </div>
  <?php endif; ?>
  <?php if ($ok): ?>
      <div class="banner banner-ok">
          <i class="material-icons">check_circle_outline</i><?= htmlspecialchars($ok) ?>
          <?php if ($pdf): ?>
              <a
                  class="btn-small pdf-link-btn"
                  target="_blank"
                  href="<?= htmlspecialchars($pdf) ?>"
              >Download PDF</a>
          <?php endif; ?>
      </div>
  <?php endif; ?>

  <form method="POST" action="">
    <input type="hidden" name="action" value="fetch_patient">
    <div class="row">
        <div class="col s12 grey-text" style="text-align:center; margin-bottom: 15px;">
            Enter an MRN to fetch a patient, or leave it blank and enter a name and age to create a new one.
        </div>
    </div>
    <div class="row valign-wrapper" style="align-items: flex-start;">
        <div class="input-field col s12 m4 l3">
            <i class="material-icons prefix">account_circle</i>
            <input id="mrn_in" name="mrn" type="text" value="<?= htmlspecialchars($mrnVal) ?>" autocomplete="off">
            <label for="mrn_in">Patient MRN (Optional)</label>
        </div>
        <div class="input-field col s12 m4 l4">
            <i class="material-icons prefix">person</i>
            <input id="full_name_in" name="full_name" type="text" autocomplete="off">
            <label for="full_name_in">Full Name (if new)</label>
        </div>
        <div class="input-field col s12 m2 l2">
            <i class="material-icons prefix">cake</i>
            <input id="age_in" name="age" type="number" autocomplete="off">
            <label for="age_in">Age (if new)</label>
        </div>
        <div class="col s12 m2 l2" style="padding-top:20px;">
            <button class="btn waves-effect" style="width:100%;">Proceed</button>
        </div>
    </div>
  </form>


<?php if ($pData): ?>
  <div class="patient-box">
    <p>MRN: <?= htmlspecialchars($pData['mrn']) ?></p>
    <p>Name: <?= htmlspecialchars($pData['full_name']) ?></p>
    <p>Age: <?= $pData['age'] > 0 ? htmlspecialchars($pData['age'] . ' ' . $pData['age_unit']) : 'N/A' ?></p>
    <p>Gender: <?= htmlspecialchars($pData['gender']) ?></p>
    <a class="btn-flat waves-effect" href="?clear_patient=1">Clear Patient</a>
  </div>

  <form method="POST" action="" style="margin-top:30px;">
    <input type="hidden" name="action" value="create_order">
    <input type="hidden" name="mrn" value="<?= htmlspecialchars($pData['mrn']) ?>">

    <div class="search-wrapper row">
      <div class="input-field col s12 m8 l6 offset-l3">
        <i class="material-icons prefix">search</i>
        <input id="searchBox" type="search" autocomplete="off">
        <label for="searchBox">Search Tests</label>
      </div>
    </div>

    <div class="tests-box row" id="testList">
      <?php foreach ($tests as $t): ?>
        <div
            class="col s12 m6 test-item"
            data-name="<?= strtolower($t['test_name']) ?>"
        >
          <label>
            <input
                type="checkbox"
                class="filled-in test-cb"
                name="selected_tests[]"
                value="<?= $t['test_id'] ?>"
                data-price="<?= $t['test_price'] ?>"
            >
            <span><?= htmlspecialchars($t['test_name']) . ' (' . number_format($t['test_price'], 2) . ' PKR)' ?></span>
          </label>
        </div>
      <?php endforeach; ?>
    </div>

    <p style="text-align:right;margin-top:20px;font-size:1.2rem;">
        Total: PKR <span id="totalAmt">0.00</span>
    </p>

    <div class="row center-align" style="margin-top:30px;">
      <button class="btn btn-large green waves-effect" name="save_and_print">
        <i class="material-icons left">print</i>Create Order &amp; Print Invoice
      </button>
    </div>
  </form>
<?php elseif (!$err && !$ok): ?>

<?php endif; ?>

</div>
</main>

<?php include __DIR__ . '/includes/footer.php'; ?>

<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded', () => {
  M.updateTextFields();
  const list = document.getElementById('testList'),
        tot  = document.getElementById('totalAmt');
  const calc = () => {
    let s = 0;
    list && list.querySelectorAll('.test-cb:checked').forEach(cb =>
      s += parseFloat(cb.dataset.price || 0)
    );
    tot.textContent = s.toFixed(2);
  };
  list && list.addEventListener('change', e => {
    if (e.target.classList.contains('test-cb')) calc();
  });
  calc();

  const sb = document.getElementById('searchBox');
  sb && sb.addEventListener('input', function () {
    const q = this.value.toLowerCase().trim();
    list.querySelectorAll('.test-item').forEach(i => {
      i.style.display = i.dataset.name.includes(q) ? 'block' : 'none';
    });
  });

  <?php if ($trigger && $pdf): ?>
    try { window.open('<?= htmlspecialchars($pdf) ?>', '_blank'); } catch (e) {}
  <?php endif; ?>
});
</script>
</body>
</html>